# Generated by Django 3.2.8 on 2021-11-02 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50000)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientFood',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IEapp.food')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50000)),
                ('score', models.IntegerField(default=0)),
                ('within_food', models.ManyToManyField(through='IEapp.IngredientFood', to='IEapp.Food')),
            ],
        ),
        migrations.CreateModel(
            name='scraper_articles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('article_url', models.CharField(max_length=50000)),
                ('article_data', models.CharField(max_length=50000)),
                ('classification_result', models.IntegerField(default=0)),
                ('ingredients_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IEapp.ingredients')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientfood',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IEapp.ingredients'),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredient_content',
            field=models.ManyToManyField(through='IEapp.IngredientFood', to='IEapp.Ingredients'),
        ),
    ]
