# Generated by Django 3.2.8 on 2021-10-24 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper_articles',
            name='ingredients_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IEapp.ingredients'),
        ),
    ]
