# Generated by Django 3.2.8 on 2021-11-02 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='scraper_articles',
            new_name='ScraperArticles',
        ),
    ]
