# Generated by Django 3.2.8 on 2021-11-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0003_auto_20211101_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ingredient_content',
            field=models.ManyToManyField(through='IEapp.ingredient_food', to='IEapp.Ingredients'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='within_food',
            field=models.ManyToManyField(through='IEapp.ingredient_food', to='IEapp.Food'),
        ),
    ]
