# Generated by Django 3.2.8 on 2021-10-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0003_auto_20211024_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ingredient_content',
        ),
    ]
