# Generated by Django 3.2.8 on 2021-10-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0005_food_ingredient_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scraper_articles',
            name='classification_result',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scraper_articles',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
