# Generated by Django 3.2.8 on 2021-11-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0005_auto_20211102_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IEapp.food')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IEapp.ingredient')),
            ],
        ),
        migrations.DeleteModel(
            name='IngredientFood',
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(through='IEapp.Composed', to='IEapp.Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='foods',
            field=models.ManyToManyField(through='IEapp.Composed', to='IEapp.Food'),
        ),
    ]
