# Generated by Django 3.2.8 on 2021-11-02 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0006_auto_20211102_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredient_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50000)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='scraper_articles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('article_url', models.CharField(max_length=50000)),
                ('article_data', models.CharField(max_length=50000)),
                ('classification_result', models.IntegerField(default=0)),
                ('ingredients_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IEapp.ingredients')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='scraperarticle',
            name='ingredients_id',
        ),
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Composed',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='ScraperArticle',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='within_food',
            field=models.ManyToManyField(through='IEapp.ingredient_food', to='IEapp.food'),
        ),
        migrations.AddField(
            model_name='ingredient_food',
            name='Food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IEapp.food'),
        ),
        migrations.AddField(
            model_name='ingredient_food',
            name='Ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IEapp.ingredients'),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredient_content',
            field=models.ManyToManyField(through='IEapp.ingredient_food', to='IEapp.ingredients'),
        ),
    ]
