# Generated by Django 3.2.8 on 2021-10-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0006_auto_20211027_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_food',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
