# Generated by Django 3.2.8 on 2021-11-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0008_auto_20211102_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='within_food',
            field=models.ManyToManyField(through='IEapp.IngredientFood', to='IEapp.Food'),
        ),
    ]
