# Generated by Django 3.2.8 on 2021-11-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0009_alter_ingredient_within_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientfood',
            old_name='food',
            new_name='foods',
        ),
        migrations.RenameField(
            model_name='ingredientfood',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='within_food',
            field=models.ManyToManyField(through='IEapp.IngredientFood', to='IEapp.Food'),
        ),
    ]
