# Generated by Django 3.2.8 on 2021-11-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0010_auto_20211102_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='within_food',
            field=models.ManyToManyField(through='IEapp.IngredientFood', to='IEapp.Food'),
        ),
        migrations.DeleteModel(
            name='ingredient_food',
        ),
        migrations.DeleteModel(
            name='ingredients',
        ),
    ]
