# Generated by Django 3.2.8 on 2021-11-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0011_auto_20211104_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='within_food',
            field=models.ManyToManyField(through='IEapp.IngredientFood', to='IEapp.Food'),
        ),
    ]
