# Generated by Django 3.2.8 on 2021-11-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0017_alter_ingredient_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='foods',
            field=models.ManyToManyField(through='IEapp.IngredientFood', to='IEapp.Food'),
        ),
        migrations.AlterField(
            model_name='scraperarticle',
            name='ingredients_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IEapp.ingredient'),
        ),
    ]
