# Generated by Django 3.2.8 on 2021-11-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0019_alter_ingredient_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='foods',
            field=models.ManyToManyField(through='IEapp.IngredientFood', to='IEapp.Food'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
