# Generated by Django 3.2.4 on 2021-11-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0026_alter_ingredient_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='foods',
            field=models.ManyToManyField(through='IEapp.IngredientFood', to='IEapp.Food'),
        ),
        migrations.AlterModelTable(
            name='food',
            table='Food',
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='Ingredient',
        ),
        migrations.AlterModelTable(
            name='ingredientfood',
            table='ingredient_food',
        ),
        migrations.AlterModelTable(
            name='scraperarticle',
            table='ScraperArticle',
        ),
    ]
