# Generated by Django 3.2.4 on 2021-11-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEapp', '0027_auto_20211109_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='foods',
            field=models.ManyToManyField(through='IEapp.IngredientFood', to='IEapp.Food'),
        ),
    ]
